services:
  postgres:
    image: postgres:16.10-alpine3.22
    container_name: ouestmonfric-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ouestmonfric
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8.2.2-alpine3.22
    container_name: ouestmonfric-redis
    restart: always
    ports:
      - "6379:6379"

  api:
    build: .
    container_name: ouestmonfric-api
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: ouestmonfric
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      NODE_ENV: production
    depends_on:
      - postgres
      - redis
    # volumes supprimés pour la production

volumes:
  postgres_data: